Do not run probabilities script if cmd not found
Signed-off-by: Tim Henderson <tim.tadh@gmail.com>

diff --git a/bin/probabilities b/bin/probabilities
--- a/bin/probabilities
+++ b/bin/probabilities
@@ -9,6 +9,11 @@ else
 	exit 1
 fi
 
+if ! which selection_probability &> /dev/null; then
+	echo "selection_probability program not found"
+	exit 1
+fi
+
 for path in $(find $1 -name 'matrices.json'); do
 	selection_probability -m $path -o $(dirname $path)/pattern.pr
 done
